context:
  version: "1.8.3"
  python_min: '3.11'

package:
  name: any-llm-sdk
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/a/any-llm-sdk/any_llm_sdk-${{ version }}.tar.gz
    sha256: af87f1beb95a1fc87746006f36cdd6f9dfb11c1e5bb0022e6e751f9fe3aa3f74

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=48
    - setuptools_scm >=6.3.1
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >2,<3
    - openai >=1.99.3
    - rich
    - httpx
    - typing-extensions

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - any_llm
      pip_check: true

about:
  homepage: https://github.com/mozilla-ai/any-llm
  summary: Communicate with an LLM provider using a single interface
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://mozilla-ai.github.io/any-llm/

extra:
  recipe-maintainers:
    - moritzwilksch
