context:
  version: "1.29.0"

package:
  name: any-llm-sdk
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/a/any-llm-sdk/any_llm_sdk-${{ version }}.tar.gz
    sha256: 35ca9051a2c52281429f0465a01b83e3982a1f6048a20dec69841f27a1f3763f

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=48
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >2,<3
    - openai >=2.18.0
    - openresponses-types >=2.4.0,<3
    - anthropic >=0.119.0
    - rich
    - httpx
    - typing-extensions >=4.5.0

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - any_llm
      pip_check: true

about:
  homepage: https://github.com/mozilla-ai/any-llm
  summary: Communicate with an LLM provider using a single interface
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://mozilla-ai.github.io/any-llm/

extra:
  recipe-maintainers:
    - moritzwilksch
